CREATE PROCEDURE [dbo].[ABC_CHANGE] @PRODUCT_ID INT, @UNIT_PRICE MONEY
AS
	BEGIN
	DECLARE @BEFORE_CHANGE money
	set @BEFORE_CHANGE = (SELECT UNITPRICE FROM ABC where ProductID = @PRODUCT_ID)
	INSERT INTO DBA (REASON, DATE1, before_change, after_change)
	VALUES ('UPDATE', GETDATE(), @BEFORE_CHANGE, @UNIT_PRICE)
	END
	BEGIN
	UPDATE ABC 
	SET UnitPrice = @UNIT_PRICE, ModifiedDate = GETDATE()
	WHERE ProductID = @PRODUCT_ID
	END
GO

-- alter procedure

ALTER PROCEDURE [dbo].[ABC_CHANGE] 
@REASON nvarchar (30), @PRODUCT_ID INT, @NEW_VALUE MONEY
AS
	BEGIN
	DECLARE @OLD_VALUE money
	SET @OLD_VALUE = (SELECT UNITPRICE FROM ABC where ProductID = @PRODUCT_ID) 
	INSERT INTO DBA (REASON, PRODUCT_ID, OLD_VALUE, NEW_VALUE, DATE1)
	VALUES (@REASON, @PRODUCT_ID, @OLD_VALUE, @NEW_VALUE, GETDATE())
	END
	BEGIN
	UPDATE ABC 
	SET UnitPrice = @NEW_VALUE, ModifiedDate = GETDATE()
	WHERE ProductID = @PRODUCT_ID
	END
GO