CREATE PROCEDURE [dbo].[ABC_CHANGE] @PRODUCT_ID INT, @UNIT_PRICE MONEY
AS
	BEGIN
	DECLARE @BEFORE_CHANGE money
	set @BEFORE_CHANGE = (SELECT UNITPRICE FROM ABC where ProductID = @PRODUCT_ID)
	INSERT INTO DBA (REASON, DATE1, before_change, after_change)
	VALUES ('UPDATE', GETDATE(), @BEFORE_CHANGE, @UNIT_PRICE)
	END
	BEGIN
	UPDATE ABC 
	SET UnitPrice = @UNIT_PRICE, ModifiedDate = GETDATE()
	WHERE ProductID = @PRODUCT_ID
	END
GO