ALTER PROCEDURE [dbo].[ABC_CHANGE] @REASON nvarchar (30), @PRODUCT_ID INT, @NEW_VALUE MONEY
AS
IF @REASON = 'UPDATE' OR @REASON = 'update'
	BEGIN
	DECLARE @OLD_VALUE money
	SET @OLD_VALUE = (SELECT UNITPRICE FROM ABC where ProductID = @PRODUCT_ID) 
	INSERT INTO DBA (REASON, PRODUCT_ID, OLD_VALUE, NEW_VALUE, DATE1)
	VALUES (@REASON, @PRODUCT_ID, @OLD_VALUE, @NEW_VALUE, GETDATE())
	UPDATE ABC 
	SET UnitPrice = @NEW_VALUE, ModifiedDate = GETDATE()
	WHERE ProductID = @PRODUCT_ID
	END;
ELSE
	PRINT 'NIEDOZWOLONA WARTOŚĆ PARAMETRU REASON'
GO